wd: desired/output/path
dada2_sm_dir: /github/download/dir/dada2_v1.6 # should contain the databases

orig_fastqs: /dir/raw_fastq
filtered_fastqs: 01_filtered_fastq
error_model_dir: 02_error_models
seqtables_dir: 03_sequence_tables
taxonomy_dir: 04_assigned_taxonomies
merged_seqtab_dir: 04_merged_sequence_table
analysis_dir: 05_analyses

filter_and_trim:
  r1_trunc: 270
  r2_trunc: 240
taxonomy:
  - rdp
  - silva
phyloseq:
  sample_data_table: path/to/sampleData.txt
  min_sample_reads: 1000
  min_samples: 3
  min_amplicon_reads: 10
