name: dada2v1.6
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.5.3
  - snakemake=5.4.2
  - fastqc=0.11.8
  - multiqc=1.6
  - bioconductor-dada2=1.6.0
  - bioconductor-phyloseq=1.22.3
  - bioconductor-genefilter=1.60
  - r-readr
  - r-dplyr
